// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77RMHUE5027felE2LuHDYBIyIQgqVQ8k',
    appId: '1:1051870297015:web:9cdfc3963fbaa8fa344632',
    messagingSenderId: '1051870297015',
    projectId: 'srocks-app',
    authDomain: 'srocks-app.firebaseapp.com',
    storageBucket: 'srocks-app.firebasestorage.app',
    measurementId: 'G-7XH83H5SJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3feXTBNPI4RuM3gsHG-8ptDQXwgbH9aI',
    appId: '1:1051870297015:android:1f8a68cbd3593d93344632',
    messagingSenderId: '1051870297015',
    projectId: 'srocks-app',
    storageBucket: 'srocks-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36QBw-NR5XtU6t_mfscm3sQRE4JTXlUg',
    appId: '1:1051870297015:ios:ab8874511e7efbb5344632',
    messagingSenderId: '1051870297015',
    projectId: 'srocks-app',
    storageBucket: 'srocks-app.firebasestorage.app',
    iosBundleId: 'com.example.srocksapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36QBw-NR5XtU6t_mfscm3sQRE4JTXlUg',
    appId: '1:1051870297015:ios:ab8874511e7efbb5344632',
    messagingSenderId: '1051870297015',
    projectId: 'srocks-app',
    storageBucket: 'srocks-app.firebasestorage.app',
    iosBundleId: 'com.example.srocksapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77RMHUE5027felE2LuHDYBIyIQgqVQ8k',
    appId: '1:1051870297015:web:23848824576cdec4344632',
    messagingSenderId: '1051870297015',
    projectId: 'srocks-app',
    authDomain: 'srocks-app.firebaseapp.com',
    storageBucket: 'srocks-app.firebasestorage.app',
    measurementId: 'G-GVWZXL0JMJ',
  );
}
